# Generated by Django 3.2.6 on 2021-08-26 13:42

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('title',))),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('good_deal', models.CharField(max_length=255)),
                ('price_deal', models.IntegerField()),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.offers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'deal',
                'verbose_name_plural': 'deals',
            },
        ),
    ]
